config/routes.rb
Rails.application.routes.draw do
  # get 'reservations/index'
  get '/pages', to: 'pages#index'
  root 'sessions#new'
  resources :users
  resources :reservations
  # post 'reservations/:id/edit', to: 'reservations#edit'
  # get 'reservations/:id/delete', to: 'reservations#delete'
  # get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: "sessions#destroy"
  # post '/', to: 'sessions#new'
  
  resources :manages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manage.rb
class Manage < ApplicationRecord
  # belongs_to :user
  
  validates :start_time, presence: true
  validates :last_time, presence: true
  validates :finish_time, presence: true
  
  
  scope :start_time, -> { order(start_time: :asc) }
  ransacker :created_at, callable: proc { Arel.sql('DATE(created_at)') }
end

app/controllers/manages_controller.rb
class ManagesController < ApplicationController
  
 
  
  def index
   
  
    # if !params[:q].blank?
      
      # @q = Reservation.ransack(params[:q])
      # @res = @q.result(distinct: true)
    # @manages = Manage.where(created_at: params[:created_at].in_time_zone.all_day).order(start_time: 'ASC')
      
      @q = Manage.ransack(params[:q])
      @manages = @q.result(distinct: true)
      
      # @res = Reservation.where(reserve_day: params[:created_at]).order(reserve_day: 'ASC')
      @q = Reservation.ransack(params[:q])
      @res = @q.result(distinct: true)
    # elsif params[:created_at] && params[:sort_coulmn] == "table_number" && params[:sort_type] == "ASC"
    #   @manages = Manage.where(created_at: params[:created_at].in_time_zone.all_day).order(table_number: :ASC)
    #   @res = Reservation.all.order(reserve_day: 'ASC')
    
    # elsif params[:created_at]  && params[:sort_coulmn] == "member"
    #   @manages = Manage.where(created_at: params[:created_at].in_time_zone.all_day).order(member: :desc) 
    #   @res = Reservation.all.order(reserve_day: 'ASC')
    
    # else
    # # #   # @q = Manage.ransack(params[:q])
    # # #   # @manages = @q.result(distinct: true)
    # #   @q = Manage.all.order(start_time: 'ASC')
    #   # @res = Reservation.all
    # end
    
  end
  
  def new
    @manage = Manage.new
  end
 
  def create
    
    @manage = Manage.new(manage_params)
    if @manage.save
      redirect_to manages_path, success: '予約の登録が出来ました。'
    else
      flash.now[:danger] = '予約の登録が出来ませんでした。'
      render :new
    end
  end
  
  def edit
    @manage = Manage.find(params[:id])
  end
  def update
    @manage = Manage.find(params[:id])
   
    if @manage.update(manage_params) || @manage.update(check_parmas)
      redirect_to manages_path(params[:created_at]), success: '更新しました'
    else
      flash.now[:danger] = '更新失敗しました'
      render :new
    end
  end
  
  def destroy
    @manage = Manage.find(params[:id])
    @manage.destroy
    redirect_to manages_path
  end
 
  private
   def manage_params
     params.require(:manage).permit(:table_number,:member, :start_time, :last_time, :finish_time, :course, :coupon, :remarks, :created_at)
   end
   def check_params
     params.require(:manage).permit(:last, :accounting, :closed)
   end
   
end

app/helpers/manages_helper.rb
module ManagesHelper
 
end

app/views/manages/_form.html.erb
<div class="row">
 
     <div class="col-md-offset-2 col-md-8">
      <h2>管理表登録</h2>
      <div class="btn-manage">
        <a href="/manages">
          <%= button_tag '管理表ページへ' %>
         </a>
       </div>
      <div class="contents">
          <%= form_for @manage do |f| %>
            <div class="form_group  col-md-5">
                <%= f.label :卓番, class: 'text' %>
                <%= f.select :table_number,[10,11,12,13,14,15,20,21,22,23,24,25,27,30,31,33,34,36,40,41,42,43,44,45,46],{include_blank: '選択'},  class: 'form-control' %>
            </div>
            <div class="form_group col-md-offset-2 col-md-5">
                <%= f.label :人数, class: 'text' %>
                <%= f.text_field :member, class: 'form-control' %>
            </div>
            <div class="form_group col-md-5">
                <%= f.label :開始時間, class: 'text' %>
                <%= f.time_field :start_time, class: 'form-control' %>
            </div>
            <div class="form_group col-md-offset-2 col-md-5">
                <%= f.label :Last時間, class: 'text' %>
                <%= f.time_field :last_time, class: 'form-control' %>
            </div>
            <div class="form_group col-md-5">
                <%= f.label :終了時間, class: 'text' %>
                <%= f.time_field :finish_time, class: 'form-control' %>
            </div>
            <div class="form_group col-md-offset-2 col-md-5">
                <%= f.label :コース名, class: 'text' %>
                <%= f.select :course, ["Aコース","Bコース","Cコース","飲み放題","F"], {include_blank: '選択してください'}, class: 'form-control' %>
            </div>
            <div class="form_group col-md-5">
                <%= f.label :割引, class: 'text' %>
                <%= f.select :coupon,["ホットペッパー","ぐるなび","食べログ","LINE"], {include_blank: '選択してください'}, class: 'form-control' %>
            </div>
            <div class="form_group col-md-offset-2 col-md-5">
                <%= f.label :備考欄, class: 'text' %>
                <%= f.text_field :remarks, class: 'form-control' %>
            </div>
            
            
            <% if request.path_info == new_manage_path %>
            
              <div class="col-md-offset-3 col-md-3">
               <%= f.submit "登録", class: "btn-block" %>
              </div>
              <div class="col-md-offset-3 col-md-3">
                <%= button_tag 'クリア', type:'reset', class: 'btn-block' %>
              </div>
              <% else %>
                <div class="form_group col-md-3 col-md-offset-1">
                    <%= f.label :ラスト済, class: 'text' %>
                    <%= f.radio_button :last, :済 %>
                    <%= f.label :ラスト未, class: 'text' %>
                    <%= f.radio_button :last, :未 %>
                </div>
                <div class="form_group col-md-offset-1 col-md-3">
                    <%= f.label :会計済, class: 'text' %>
                    <%= f.check_box :accounting, {class: 'form_control'}, true %>
                    <%= f.label :会計未, class: 'text' %>
                    <%= f.check_box :accounting, {class: 'form_control'}, false %>
                </div>
                <div class="form_group col-md-offset-1 col-md-3">
                    <%= f.label :退店済, class: 'text' %>
                    <%= f.check_box :closed, {class: 'form_control'}, true %>
                    <%= f.label :退店未, class: 'text' %>
                    <%= f.check_box :closed, {class: 'form_control'}, false %>
                </div>
                 <div class="col-md-offset-3 col-md-3">
                   <%= f.submit "更新", class: "btn-block" %>
                 </div>
                 <div class="col-md-offset-3 col-md-3">
                    <%= link_to "戻る", manages_path, class: 'btn-block' %>
                 </div>
            <% end %>
          <% end %>
      </div>
      
     </div>
    </div>

app/views/manages/edit.html.erb
<div class="index-wrapper">
 <div class="index-container">
   <h2>管理表更新</h2>
   
     <%= render partial: "form" %>
   
   </div>
  </div>

app/views/manages/index.html.erb
<div class="index-wrapper">
 <div class="index-container">
   <h2>管理表画面</h2>
  <div class="row">
 
   <div class="col-md-offset-2 col-md-6">
     <div class="btn-manage">
       <%= search_form_for(@q, url: manages_path) do |f| %>
          <%= f.date_field :created_at_eq, value: Time.now.strftime("%Y-%m-%d") %>
          <%= f.submit "検索" %>
       <% end %>
       <%= button_to '管理登録へ', new_manage_path, method: :get  %>
        
     </div>
     
    <div class="contents">
     <h1>管理表</h1>
     </div>
     <table>
      <thead>
        <tr>
         <td></td>
         
         
         <th><%= sort_link(@q, :table_number, "卓番") %></th>
         <th><%= sort_link(@q, :member, "人数") %></th>
         <th><%= sort_link(@q, :start_time, "開始時間") %></th>
         <th><%= sort_link(@q, :last_time, "last時間") %></th>
         <th><%= sort_link(@q, :finish_time, "終了時間") %></th>
         <th><%= sort_link(@q, :course, "内容") %></th>
         <th>割引</th>
         <th>備考欄</th>
         <th>ラスト</th>
         <th>会計</th>
         <th>退店</th>
        </tr>
      </thead>
      
      <tbody>
       
        <% @manages.each do |manage| %>
         
          <tr>
            <td></td>
            <td><%= manage.table_number %></td>
            <td><%= manage.member %></td>
            <td><%= l manage.start_time, format: :normal %></td>
            <td>
              <% if manage.last_time <= Time.now %>
               <div class="time-yellow"><%= l manage.last_time, format: :normal %></div>
              <% else %>
               <div class="time-white"><%= l manage.last_time, format: :normal %></div>
              <% end %>
            </td>
            <td><%= l manage.finish_time, format: :normal %></td>
            <td><%= manage.course %></td>
            <td><%= manage.coupon %></td>
            <td><%= manage.remarks %></td>
            
            <td><%= manage.last %></td>
            <td><%= manage.accounting %></td>
            <td><%= manage.closed %></td>
            <td><%= check_box_tag 'manage[last]', true, false %></td>
          
            <td><%= link_to "/manages/#{manage.id}/edit" do %>
             <button type="button" class="btn btn-outline-primary">
              <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> 更新
             </button>
             <% end %>
             </td>
             
             <td><%= link_to "/manages/#{manage.id}", method:"delete", data: { confirm: '削除しますか？'} do %>
             <button type="button" class="btn btn-outline-primary">
               <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> 削除
             </button>
             <% end %>
             </td>
          
          </tr>  
        <% end %>
        
        
      </tbody>
     </table>
  </div>
   <div class="col-md-3">
     <h4>本日の予約</h4>
       <table>
         <thead>
           <tr>
             <td></td>
             <th>予約時間</th>
             <th>予約名</th>
             <th>予約人数</th>
             <th>予約内容</th>
           </tr>
         </thead>
         <tbody>
          <% @res.each do |reservation| %>
           <tr>
            <td></td>
            <td><%= l reservation.reserve_day, format: :normal %></td>
            <td><%= reservation.reserve_name %></td>
            <td><%= reservation.member %></td>
            <td><%= reservation.course %></td>
           </tr>
          <% end %>
         </tbody>
       </table>
   </div>
 </div>
</div>

app/views/manages/new.html.erb
<div class="index-wrapper">
 <div class="index-container">
   <h2>管理表画面</h2>
    
    <%= render partial: "form"%>
    
 </div>
</div>